### ISSUE TITLE
component lifecycle functions

### ISSUE THREAD

**Issue by ghost** [jeluard/hipo#27]
Thanks for Hipo, great library with great potential
Question: How can I implement some kind of lifecyle functions in Hipo, e.g.
execute some code before/after an element is created/deleted in the DOM?

Example use case:
I'm generating a chart using Hiccup, and use Hipo to update the DOM representation when the underlying data changes. But for the axis of the chart I'd like to use D3.js axis, which manipulates the DOM directly.

In the ReactJS world there is component-did-mount, will-mount etc. that is used to support cases like this. See also https://github.com/Day8/re-frame/wiki/Creating-Reagent-Components

Perhaps interceptors could help here, but it is difficult to identify what a 'component'  is, especially if the reconciler decided to create a whole tree in one single action: only one interceptor action is created even if this tree contains multiple components.

So perhaps a function generating Hiccup could be considered a single component, and with some macro or other ways, Hipo could recognise these as components and execute the lifecycle functions (if provided)

**Comment by jeluard** [comment]
Yes your last suggestion is probably the way to go. Create several higher level components with hipo that you will manually insert in the DOM. Then it's up to you to call your lifecycle functions when needed.

I would suggest looking at WebComponents. [lucuma](https://github.com/jeluard/lucuma), a ClojureScript wrapper, might help here. 
You can find some examples in this other project [picada](https://github.com/jeluard/picada).
