### ISSUE TITLE
SVG element will be added to the DOM, but not displayed until edited in console

### ISSUE THREAD

**Issue by jmromrell** [jeluard/hipo#28]
I am running into the exact problem described [here](https://stackoverflow.com/questions/24961151/svg-wont-show-until-i-edit-the-element-in-chrome-developer-tools) when trying to add an svg element to the DOM using hipo.

This is the code I use to add the svg element:

```clojure
(.appendChild (.getElementById js/document "app")
  (hipo/create
    [:svg#svg {:style {:background-color "green"} :width 500 :height 500 :xmlns "http://www.w3.org/2000/svg"}
      [:line {:x1 0 :y1 0 :x2 500 :y2 500 :style {:stroke "red" :stroke-width 2}}]]
    {:attribute-handlers [hipo-attr/style-handler]}))
```

After this has run, I don't see it on the page, but I can inspect the DOM and see that it has been added correctly:

```html
<svg width="500" height="500" xmlns="http://www.w3.org/2000/svg" id="svg" style="background-color: green;">
    <line x1="0" y1="0" x2="500" y2="500" style="stroke: red; stroke-width: 2;"></line></svg>
```

On the page it is rendered as having width and height of zero. I have found that I can make it visible by using the developer tools in Chrome to "edit as html" the svg element and adding an extra space somewhere (any change to the HTML will cause it to appear).

I haven't found any other way to make it appear (resizing window, adding/removing elements from DOM, hiding and then showing the parent element, all to try to trigger a redraw).

**Comment by jeluard** [comment]
You must use the `svg` namespace when creating svg elements (see doc [here](https://github.com/jeluard/hipo#namespaces)).

Let me know if that works for you.

**Comment by jmromrell** [comment]
That worked excellently, thank you. My apologies for overlooking that. :)

**Comment by jeluard** [comment]
Great! Glad it did!
